### ISSUE TITLE
will you add some tasks like, tensor parallel, checkpoint and some related training strategies for speed up

### ISSUE THREAD

**Issue by powermano** [Strivin0311/llms-learning#3]

**Comment by powermano** [comment]
As i already finished all the tasks, and want some training strategies, like deepspeed that uses amp, smart gradient accumulation, fp16 gradient compress, zero1, zero2 and so on.  

by the way, i want more tasks about [megatron](https://github.com/NVIDIA/Megatron-LM/tree/main/megatron) or some vllm related tasks.

thanks.

**Comment by Strivin0311** [comment]
Hi~Thank you for your active participation! 

To answer your question:
- **For this online class**, probably not, as the strategies you mentioned are out the scope of the syllabus, based on what I've been informed from the teacher. Future assignments may focus more on LLM applications rather than LLM systems.
- **As for myself**, it’s possible, since I work as an LLM infra engineer. However, I can't guarantee a specific timeline due to my current workload (~sorry).

I recommend that you directly explore the source codes of off-the-shelf frameworks such as Megatron, Transformer Engine, DeepSpeed, etc, as I believe you're fully capable of diving into these resources.
